### PR TITLE
created and added skeleton for whislinWhilliesMines.js

### PR DESCRIPTION
**Pull request by JCrippen01**
# Description

Created a skeleton file for whistlinWhilliesMines.js
Fixes # Lays out frame work to add HTML compents to main.js

## Type of change

Please delete options that are not relevant.

- - [ ] New feature (non-breaking change which adds functionality)

# Still needs done?

This item will need to be updated to match naming conventions of all other modules.
Will need imports added once naming conventions are set.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings

### CODE REVIEW

**Review by SBorghesani — APPROVED** [review]
Love the slogan. Way to nail that BEM naming as well!

**Comment by JCrippen01** [comment]
Updated Issues please review again.

**Review by SBorghesani — APPROVED** [review]
Looks good to me now that the 'Whistling's' are all the same.

**Review by SharifRashed — APPROVED** [review]
Good work. Looks good

**Review by galmodovar — APPROVED** [review]
Looks good to me 👍

**Comment by SBorghesani** [comment]
Now that we got that figured out.... It looks good to me!

**Pull request merged**
